# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-29 16:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('points', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='AccountsChallenges',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accounts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beaconQuest.Account')),
            ],
        ),
        migrations.CreateModel(
            name='Beacon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beaconUUID', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('challengeText', models.CharField(max_length=200)),
                ('challengeAnswer', models.CharField(max_length=200)),
                ('reward', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=420)),
            ],
        ),
        migrations.AddField(
            model_name='accountschallenges',
            name='beacons',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beaconQuest.Beacon'),
        ),
        migrations.AddField(
            model_name='accountschallenges',
            name='challenges',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beaconQuest.Challenge'),
        ),
        migrations.AddField(
            model_name='accountschallenges',
            name='state',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='beaconQuest.State'),
        ),
    ]
