# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-29 16:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beaconQuest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountschallenges',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beaconQuest.State'),
        ),
    ]
