# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-29 19:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beaconQuest', '0002_auto_20161029_1714'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accountschallenges',
            old_name='accounts',
            new_name='account',
        ),
        migrations.RenameField(
            model_name='accountschallenges',
            old_name='beacons',
            new_name='beacon',
        ),
        migrations.RenameField(
            model_name='accountschallenges',
            old_name='challenges',
            new_name='challenge',
        ),
        migrations.AddField(
            model_name='challenge',
            name='people',
            field=models.ManyToManyField(through='beaconQuest.AccountsChallenges', to='beaconQuest.Account'),
        ),
    ]
