# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-29 22:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beaconQuest', '0004_auto_20161029_2032'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Beacon',
        ),
        migrations.DeleteModel(
            name='State',
        ),
    ]
