# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-29 22:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beaconQuest', '0005_auto_20161029_2324'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='challenge',
            name='beacon',
            field=models.CharField(default='b2', max_length=200),
        ),
    ]
